FROM balenalib/raspberrypi3:buster-build

ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN [ "cross-build-start" ]
RUN install_packages libjpeg8-dev \
    libpng12-dev

WORKDIR /usr/src/
COPY . .
RUN [ "/bin/bash", "setup.sh" ]
RUN [ "cross-build-end" ]

CMD [ "/bin/bash", "true" ]
